stages:
  - mirror

mirror:
  tags:
    - shell
  stage: mirror
  variables:
    TARGET_REPO: "git@github.com:Citeck/ecos-community-demo.git"
    GIT_STRATEGY: clone
  cache: {}
  script:
    - mkdir -p ~/.ssh
    - echo $GITHUB_MIRROR_PRIVATE | base64 -d > ~/.ssh/id_rsa
    - echo $GITHUB_MIRROR_PUBLIC > ~/.ssh/id_rsa.pub
    - ssh-keyscan -t rsa,dsa,ecdsa github.com >> ~/.ssh/known_hosts
    - chmod -R go-rwx ~/.ssh
    - git remote add mirror $TARGET_REPO
    - git remote show mirror
    - git fetch --unshallow origin
    - git push origin '*:*'
    - git push origin --all